"""
This file saves the default (recommended) parameters
"""

# Body weight
BODY_WEIGHT = 90

# Stiffness (Nm/rad)
STIFFNESS_UPPER = 600
STIFFNESS_LOWER = 100
STIFFNESS_INTERVAL = 100

# Gear
GEAR_EFFICIENCY_CONSTANT = 0.8
GEAR_RATIO_UPPER = 150
GEAR_RATIO_LOWER = 30
GEAR_RATIO_INTERVAL = 20

# Motor
MOTOR_EFFICIENCY_CONSTANT = 0.6
MOTOR_INERTIA_UPPER = 1500
MOTOR_INERTIA_LOWER = 100
MOTOR_INERTIA_INTERVAL = 200
# TODO: non-linear interval

# Motor driver
DRIVER_VOLTAGE_LIMIT = 50
DRIVER_CURRENT_LIMIT = 10
