"""
This file allows users to input parameters according to
their specific requirements
"""

# Body weight
BODY_WEIGHT = 90

# Stiffness (Nm/rad)
STIFFNESS_UPPER = 400
STIFFNESS_LOWER = 100
STIFFNESS_INTERVAL = 20

# Gear
GEAR_EFFICIENCY_CONSTANT = 0.8
GEAR_RATIO_UPPER = 160
GEAR_RATIO_LOWER = 40
GEAR_RATIO_INTERVAL = 20

# Motor
MOTOR_EFFICIENCY_CONSTANT = 0.5
MOTOR_INERTIA_UPPER = 400
MOTOR_INERTIA_LOWER = 50
MOTOR_INERTIA_INTERVAL = 50
# TODO: non-linear interval

# Motor driver
DRIVER_VOLTAGE_LIMIT = 50
DRIVER_CURRENT_LIMIT = 10
